In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("../data/train.csv")

df.head()

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  object
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 27.9+ MB

In [4]:
df.isnull().sum()

date     0
store    0
item     0
sales    0
dtype: int64

In [5]:
df["date"] = pd.to_datetime(df["date"])

In [6]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["dayofweek"] = df["date"].dt.dayofweek
df["weekofyear"] = df["date"].dt.isocalendar().week.astype(int)
df["quarter"] = df["date"].dt.quarter
df["is_weekend"] = df["dayofweek"].isin([5, 6]).astype(int)

In [7]:
df.drop("date", axis=1, inplace=True)

In [8]:
df.head()

,store,item,sales,year,month,day,dayofweek,weekofyear,quarter,is_weekend
0,1,1,13,2013,1,1,1,1,1,0
1,1,1,11,2013,1,2,2,1,1,0
2,1,1,14,2013,1,3,3,1,1,0
3,1,1,13,2013,1,4,4,1,1,0
4,1,1,10,2013,1,5,5,1,1,1

In [9]:
X = df.drop("sales", axis=1)

y = df["sales"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

In [11]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (730400, 9)
Testing Features  : (182600, 9)
Training Labels   : (730400,)
Testing Labels    : (182600,)

In [12]:
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)

y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)

In [13]:
import os

os.listdir("../data")

['sample_predictions.csv',
 'train.csv',
 'X_test.csv',
 'X_train.csv',
 'y_test.csv',
 'y_train.csv']